export const dummyResults = {
  totalMarks: 78,
  maxMarks: 100,
  confidenceScore: 85,
  answers: [
    { question: 1, answer: "Photosynthesis is the process by which green plants convert sunlight into chemical energy, producing glucose and oxygen from CO₂ and water.", marks: 9, maxMarks: 10 },
    { question: 2, answer: "Newton's three laws: inertia, F=ma, and action-reaction. Student correctly stated all three with partial examples.", marks: 8, maxMarks: 10 },
    { question: 3, answer: "The water cycle involves evaporation, condensation, precipitation, and collection. Diagram was mostly accurate but missing transpiration.", marks: 7, maxMarks: 10 },
    { question: 4, answer: "DNA replication is semi-conservative. Student described leading and lagging strands but missed Okazaki fragments.", marks: 6, maxMarks: 10 },
    { question: 5, answer: "Explained supply and demand with correct graph. Equilibrium point identified accurately.", marks: 10, maxMarks: 10 },
    { question: 6, answer: "The French Revolution causes included financial crisis, social inequality, and Enlightenment ideas. Missing key dates.", marks: 8, maxMarks: 10 },
    { question: 7, answer: "Mitosis phases described correctly: prophase, metaphase, anaphase, telophase. Cytokinesis mentioned briefly.", marks: 9, maxMarks: 10 },
    { question: 8, answer: "Ohm's law V=IR explained with a circuit example. Calculation had a minor arithmetic error.", marks: 7, maxMarks: 10 },
    { question: 9, answer: "Essay on climate change covered greenhouse gases and rising temperatures but lacked specific data or citations.", marks: 6, maxMarks: 10 },
    { question: 10, answer: "Balanced chemical equation for combustion of methane. Products and reactants correct, coefficients accurate.", marks: 8, maxMarks: 10 },
  ],
  feedback: [
    { question: 1, strengths: "Comprehensive explanation with correct chemical equation.", improvements: "Could include the role of chlorophyll and light-dependent vs light-independent reactions." },
    { question: 2, strengths: "All three laws correctly stated with clear language.", improvements: "Examples were incomplete — provide real-world applications for each law." },
    { question: 3, strengths: "Good understanding of the basic cycle with a clear diagram.", improvements: "Include transpiration and infiltration for a complete answer." },
    { question: 4, strengths: "Correctly identified semi-conservative mechanism.", improvements: "Explain Okazaki fragments and the role of DNA ligase on the lagging strand." },
    { question: 5, strengths: "Perfect answer with accurate graph and clear explanation.", improvements: "No improvements needed — excellent work." },
    { question: 6, strengths: "Covered major causes with good historical context.", improvements: "Add specific dates (1789 storming of Bastille) and mention key figures like Robespierre." },
    { question: 7, strengths: "All phases described accurately with correct sequence.", improvements: "Elaborate on cytokinesis differences between plant and animal cells." },
    { question: 8, strengths: "Correct formula and good circuit diagram.", improvements: "Double-check arithmetic in calculations. Show unit conversions clearly." },
    { question: 9, strengths: "Good structure and awareness of key issues.", improvements: "Include specific data points, statistics, and cite scientific sources." },
    { question: 10, strengths: "Correct equation with proper balancing.", improvements: "Explain the energy changes involved and mention complete vs incomplete combustion." },
  ],
};
